version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    build: ./backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media

  frontend:
    build: ./frontend
    env_file: .env
    volumes:
      - static:/static

  gateway:
    build: ./nginx
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend